name: "test"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
env:
  jdkver_latest: 21
  WORKSPACE: /home/runner/workspace

jobs:
  test-temurin-sdk:
    name: "Temurin jdk"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        jdkconf:
          - JDK 8
          - JDK 11
          - JDK 17
          - JDK Latest
        include:
          - jdkconf: JDK 8
            jdkver: "8"
          - jdkconf: JDK 11
            jdkver: "11"
          - jdkconf: JDK 17
            jdkver: "17"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdkver || env.jdkver_latest }}
      - name: Run
        run: | 
          export OJDK_VERSION_NUMBER=${{ matrix.jdkver || env.jdkver_latest }} BOOTJDK_DIR=~/bootjdk JRESDK="jdk"
          ./testHeadlessComponents.sh
      - name: Pack results
        if: ${{ always() }}
        run: |
          tar -cf "results-jdk${{ matrix.jdkver || env.jdkver_latest }}.tar.gz" $WORKSPACE/testHeadlessComponent.log $WORKSPACE/testHeadlessComponent.jtr.xml
      - name: Upload results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          path: "results-jdk${{ matrix.jdkver || env.jdkver_latest }}.tar.gz"
        continue-on-error: true
        
  test-temurin-jre:
    name: "Temurin jre"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        jdkconf:
          - JDK 8
          - JDK 11
          - JDK 17
          - JDK Latest
        include:
          - jdkconf: JDK 8
            jdkver: "8"
          - jdkconf: JDK 11
            jdkver: "11"
          - jdkconf: JDK 17
            jdkver: "17"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdkver || env.jdkver_latest }}
      - name: Run
        run: | 
          export OJDK_VERSION_NUMBER=${{ matrix.jdkver || env.jdkver_latest }} BOOTJDK_DIR=~/bootjdk JRESDK="jre"
          ./testHeadlessComponents.sh
      - name: Pack results
        if: ${{ always() }}
        run: |
          tar -cf "results-jre${{ matrix.jdkver || env.jdkver_latest }}.tar.gz" $WORKSPACE/testHeadlessComponent.log $WORKSPACE/testHeadlessComponent.jtr.xml
      - name: Upload results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          path: "results-jre${{ matrix.jdkver || env.jdkver_latest }}.tar.gz"
        continue-on-error: true

  test-windows-jre:
    name: "Windows-jre"
    runs-on: "windows-latest"
    strategy:
      fail-fast: false
      matrix:
        jdkconf:
          - JDK 8
          - JDK 11
          - JDK 17
          - JDK Latest
        include:
          - jdkconf: JDK 8
            jdkver: "8"
          - jdkconf: JDK 11
            jdkver: "11"
          - jdkconf: JDK 17
            jdkver: "17"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdkver || env.jdkver_latest }}
      - name: Run
        shell: msys2 {0}
        run: | 
          export OJDK_VERSION_NUMBER=${{ matrix.jdkver || env.jdkver_latest }} BOOTJDK_DIR=~/bootjdk JRESDK="jre"
          ./testHeadlessComponents.sh
  test-macos-jre:
    name: "MacOS-jre"
    runs-on: "macos-latest"
    strategy:
      fail-fast: false
      matrix:
        jdkconf:
          - JDK 8
          - JDK 11
          - JDK 17
          - JDK Latest
        include:
          - jdkconf: JDK 8
            jdkver: "8"
          - jdkconf: JDK 11
            jdkver: "11"
          - jdkconf: JDK 17
            jdkver: "17"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdkver || env.jdkver_latest }}
      - name: Run
        run: | 
          export OJDK_VERSION_NUMBER=${{ matrix.jdkver || env.jdkver_latest }} BOOTJDK_DIR=~/bootjdk JRESDK="jre"
          ./testHeadlessComponents.sh
